name: quote_of_the_day
description: A Flutter package to display a random quote of the day with fancy UI.
version: 0.0.1
publish_to: 'https://pub.dev'

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # No platform-specific plugin class needed
homepage: 'https://github.com/MuhammadTalhaWaheed/quote_of_the_day'
repository: 'https://github.com/MuhammadTalhaWaheed/quote_of_the_day'
